# Generated by Django 4.2.11 on 2024-03-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_t',
            new_name='cart',
        ),
    ]
